### get all college
GET  http://localhost:4000/api/colleges


### get college by id
GET  http://localhost:4000/colleges/63f276c5ce33bff8070decbc

### delete college
DELETE   http://localhost:4000/colleges/63f2768cce33bff8070decac

###  create college
POST  http://localhost:4000/api/colleges
Content-Type: application/json

{
    "name": {
        "ar": "arabic name",
        "en": "english name"
    },
     "introduction": {
        "ar": "arabic introduction",
        "en": "english introduction"
    },
    "info": {
        "vision" : {
             "ar": "arabic introduction",
             "en": "english introduction"
        },
        "ccademicQualification" : {
             "ar": "arabic ccademicQualification",
             "en": "english ccademicQualification"
        },
        "bachelorProgram" : {
             "ar": "arabic bachelorProgram",
             "en": "english bachelorProgram"
        },
        "registrationStep" : {
             "ar": "arabic registrationStep",
             "en": "english registrationStep"
        },
        "collegeDepartment" : [{
             "ar": "arabic introduction",
             "en": "english introduction"
        }]
    },
    "counter": {
        "student": 55
    },
    "code": "dddvdssssvdddqdddvdv"
}

###  update  college
PUT  http://localhost:4000/colleges/63f276c5ce33bff8070decbc
Content-Type: application/json

{
    "nameAr": "medicen update",
    "nameEn": "name en",
    "code": "dddvdvdvffgegegegfdv",
    "location": "omdurman"
}