### get all college
GET  http://localhost:4000/api/logo


### get college by id
GET  http://localhost:4000/api/vision-mission/6401af0be2dc006818125376

### delete college
DELETE   http://localhost:4000/api/vision-mission/6401aefee2dc006818125374

###  create college
POST  http://localhost:4000/api/logo
Content-Type: application/json

{
    "title": {
        "ar": "اسم الجامعة مكتوب تحت الشعار باللغتين العربية والإنجليزية",
        "en": "The name of the university is written under the logo in both Arabic and English"
    },
    "description": {
        "ar": "يرمز إلى الجذور العميقة والأصالة",
        "en": "t symbolizes deep roots and originality"
    },
    "seqNo": 9
}

###  update  college
PUT  http://localhost:4000/api/vision-mission/6401af0be2dc006818125376
Content-Type: application/json

{
    "titleAr": "medicen update"
}